{ type: 'gif',
  id: 'Ov5NiLVXT8JEc',
  slug: 'cats-light-sabers-Ov5NiLVXT8JEc',
  url: 'https://giphy.com/gifs/cats-light-sabers-Ov5NiLVXT8JEc',
  bitly_gif_url: 'https://gph.is/1B5sZnz',
  bitly_url: 'https://gph.is/1B5sZnz',
  embed_url: 'https://giphy.com/embed/Ov5NiLVXT8JEc',
  username: '',
  source: 'https://hobolunchbox.tumblr.com/post/96197585095/the-force-is-strong-with-mr-pickles',
  rating: 'g',
  content_url: '',
  source_tld: 'hobolunchbox.tumblr.com',
  source_post_url: 'https://hobolunchbox.tumblr.com/post/96197585095/the-force-is-strong-with-mr-pickles',
  is_indexable: 1,
  import_datetime: '2014-08-30 20:50:33',
  trending_datetime: '2015-10-19 21:26:46',
  images: 
   { fixed_height_still: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200_s.gif',
        width: '356',
        height: '200' },
     original_still: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy_s.gif',
        width: '500',
        height: '281' },
     fixed_width: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200w.gif',
        width: '200',
        height: '112',
        size: '279318',
        mp4: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200w.mp4',
        mp4_size: '28771',
        webp: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200w.webp',
        webp_size: '100960' },
     fixed_height_small_still: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/100_s.gif',
        width: '178',
        height: '100' },
     fixed_height_downsampled: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200_d.gif',
        width: '356',
        height: '200',
        size: '242229',
        webp: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200_d.webp',
        webp_size: '73220' },
     preview: 
      { width: '230',
        height: '128',
        mp4: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy-preview.mp4',
        mp4_size: '37266' },
     fixed_height_small: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/100.gif',
        width: '178',
        height: '100',
        size: '240747',
        mp4: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/100.mp4',
        mp4_size: '26323',
        webp: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/100.webp',
        webp_size: '89192' },
     downsized_still: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy_s.gif',
        width: '500',
        height: '281' },
     downsized: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy.gif',
        width: '500',
        height: '281',
        size: '1802952' },
     downsized_large: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy.gif',
        width: '500',
        height: '281',
        size: '1802952' },
     fixed_width_small_still: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/100w_s.gif',
        width: '100',
        height: '56' },
     preview_webp: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy-preview.webp',
        width: '215',
        height: '121',
        size: '49358' },
     fixed_width_still: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200w_s.gif',
        width: '200',
        height: '112' },
     fixed_width_small: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/100w.gif',
        width: '100',
        height: '56',
        size: '88908',
        mp4: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/100w.mp4',
        mp4_size: '12567',
        webp: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/100w.webp',
        webp_size: '39892' },
     downsized_small: 
      { width: '500',
        height: '280',
        mp4: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy-downsized-small.mp4',
        mp4_size: '149771' },
     fixed_width_downsampled: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200w_d.gif',
        width: '200',
        height: '112',
        size: '80804',
        webp: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200w_d.webp',
        webp_size: '28020' },
     downsized_medium: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy.gif',
        width: '500',
        height: '281',
        size: '1802952' },
     original: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy.gif',
        width: '500',
        height: '281',
        size: '1802952',
        frames: '22',
        mp4: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy.mp4',
        mp4_size: '121585',
        webp: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy.webp',
        webp_size: '538448' },
     fixed_height: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200.gif',
        width: '356',
        height: '200',
        size: '863917',
        mp4: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200.mp4',
        mp4_size: '74643',
        webp: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/200.webp',
        webp_size: '265590' },
     looping: 
      { mp4: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy-loop.mp4',
        mp4_size: '968433' },
     original_mp4: 
      { width: '480',
        height: '268',
        mp4: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy.mp4',
        mp4_size: '121585' },
     preview_gif: 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/giphy-preview.gif',
        width: '123',
        height: '69',
        size: '48262' },
     '480w_still': 
      { url: 'https://media3.giphy.com/media/Ov5NiLVXT8JEc/480w_s.jpg',
        width: '480',
        height: '270' } },
  title: 'star wars fighting GIF' }
